# GitHub Actions CI Workflow
# This workflow runs on every push to the main branch
name: CI Pipeline

# Define when this workflow should run
on:
  push:
    branches: [main] # Run on push to main branch
  pull_request:
    branches: [main] # Also run on PRs to main branch

# Define the jobs to run
jobs:
  test:
    # Run this job on Ubuntu latest
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Cache pip dependencies for faster builds
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run linting (optional but good practice)
      - name: Lint with flake8
        run: |
          # Install flake8 if not in requirements
          pip install flake8
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Step 6: Run tests with pytest
      - name: Test with pytest
        run: |
          pytest --verbose --tb=short

      # Step 7: Generate test coverage report (optional)
      - name: Generate coverage report
        run: |
          pip install pytest-cov
          pytest --cov=src --cov-report=xml --cov-report=term-missing

      # Step 8: Upload coverage to codecov (optional)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
